### ISSUE TITLE
Error During Compile

### ISSUE THREAD

**Issue by TomJ1588** [landofcoder/module-magento2-mautic-integration#13]
Errors during compilation:
        Lof\Mautic\Controller\Adminhtml\Configurable\Authorize
                Incompatible argument type: Required type: \Magento\Backend\App\Action\Context. Actual type: \Magento\Framework\App\Action\Context; File: 
/bitnami/magento/vendor/landofcoder/module-mautic-integration/Controller/Adminhtml/Configurable/Authorize.php

Total Errors Count: 1

### Preconditions

Magento Version : 2.4.3-p1
Module: Latest

PageBuilder Version : 

Environment : Developer Mode

Third party modules : None

### Steps to reproduce

1. Composer Require Module
2. Enable Module
3. Compile
4.  Server Error 500

### Expected result

1. No Errors

### Actual result

1. Errors during compilation:
        Lof\Mautic\Controller\Adminhtml\Configurable\Authorize
                Incompatible argument type: Required type: \Magento\Backend\App\Action\Context. Actual type: \Magento\Framework\App\Action\Context; File: 
/bitnami/magento/vendor/landofcoder/module-mautic-integration/Controller/Adminhtml/Configurable/Authorize.php

Total Errors Count: 1

**Comment by landofcoder** [comment]
Hi @TomJ1588 

Thanks you for your reporting.
We updated the module to fix issue. You can check PR at here:
https://github.com/landofcoder/module-magento2-mautic-integration/pull/15

Latest module version: 1.0.3
