### ISSUE TITLE
Cannot use object of type stdClass as array 

### ISSUE THREAD

**Issue by TomJ1588** [landofcoder/module-magento2-mautic-integration#14]
main.CRITICAL: Error: Cannot use object of type stdClass as array in /bitnami/magento/vendor/landofcoder/module-mautic-integration/Controller/Webhook/Index.php:115
Stack trace:
#0 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(58): Lof\Mautic\Controller\Webhook\Index->execute()

### Preconditions

Magento Version : 2.4.3-p1

PageBuilder Version : The one that comes with 2.4.3-p1

Environment : Developer

Third party modules : None

### Steps to reproduce

1. Create the web hook and attempt to connect
2. It fail to connect
3. Error in log

### Expected result

1. It should work?

### Actual result

1. main.CRITICAL: Error: Cannot use object of type stdClass as array in /bitnami/magento/vendor/landofcoder/module-mautic-integration/Controller/Webhook/Index.php:115
Stack trace:
#0 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(58): Lof\Mautic\Controller\Webhook\Index->execute()

**Comment by TomJ1588** [comment]
Line 115 is trying to access the json decoded data as an array - when json_decode by default returns an object.
Fix is change line 114
$requestData = json_decode($rawData, true);

**Comment by landofcoder** [comment]
Hi @TomJ1588 

Thanks you for your reporting.
We updated the module to fix issue. You can check PR at here:
https://github.com/landofcoder/module-magento2-mautic-integration/pull/15

Latest module version: 1.0.3
